[package]
name = "evtx2bodyfile"
version = "0.1.0"
authors = ["Jan Starke <jan.starke@outofbed.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#evtx = "0.7.2"
evtx = { git = "https://github.com/janstarke/evtx" }
anyhow = "1.0.40"
clap = "2.33"
log = "0.4"
simple_logger = "1.11.0"
serde_json = "1.0"
chrono = "0.4"
